credentials:
  twitter:
    consumer_key: 'B8XQvgbHCmtnX2oyYIjQ8A'
    consumer_secret: 'vXFDjaQTyfYOkUV0t0iAxYkxv5AHOjwriOtsjrw'
    oauth_token: '437674309-iK1mrKR7hVCnmaHfK9qXiFcoAIUaKSafK9QvIQ5J'
    oauth_token_secret: 'euo6X3fOyMlAwpkV5626PFrTPH7370lKqauPmd9VI'

  mailer:
    address: 'mail.locum.ru'
    port: 25
    user_name: 'no-reply@appletunity.ru'
    password: '1xEaD419sl4dw38y'
    authentication: 'plain'